name: Primary

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  library:
    name: Library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7.0.1
      - name: Install uv
        uses: astral-sh/setup-uv@v10.2.0
      - name: Install Python
        run: uv python install 3.11 3.12 3.13 3.14
      - name: Install Dependencies
        run: uv sync --locked --dev
      - name: Run ruff
        run: uv run ruff check .
      - name: Run pytest
        run: uv run python -m pytest --cov-report=xml
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v7.1.1
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Install tox
        run: uv tool install tox --with tox-uv
      - name: Run tox
        run: uv run tox
      - name: Build Package
        run: uv build
  documentation-build:
    name: Documentation Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7.0.1
      - name: Install uv
        uses: astral-sh/setup-uv@v10.2.0
      - name: Install Python
        run: uv python install
      - name: Install Dependencies
        run: uv sync --locked --dev
      - name: Build Documentation
        run: uv run zensical build --clean
      - name: Upload Documentation
        uses: actions/upload-pages-artifact@v5.0.0
        with:
          path: site/
  documentation-deploy:
    name: Documentation Deployment
    needs: documentation-build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: pages
      cancel-in-progress: false
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v6.0.0
      - name: Deploy Documentation
        uses: actions/deploy-pages@v5.0.1
        id: deployment
